name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v2
    # N.B. Github action runners have GHC 9.4.1 pre-installed.
    # I will keep this here in case we need to override version.
    # - uses: haskell/actions/setup@v2
    #   with:
    #     ghc-version: '9.2.2'
    #     cabal-version: '3.6.2'

    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Install ubuntu packages
      run: sudo apt-get install -y libcairo2 libcairo2-dev imagemagick
    - name: Install dependencies
      run: |
        cabal update
        cabal build all --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build all --enable-tests --enable-benchmarks all
    - name: Autograding
      uses: education/autograding@v1
    - name: Archive image
      uses: actions/upload-artifact@v4
      with:
        name: image
        path: |
          image.png
